/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpus.app;

import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class dTransaksiKembali extends javax.swing.JDialog {

    DaoPerpus dtPerpus;

    /**
     * Creates new form dTransaksiKembali205314162
     */
    public dTransaksiKembali(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public dTransaksiKembali(java.awt.Frame parent, boolean modal, DaoPerpus dtPerpus) {
        super(parent, modal);
        initComponents();
        this.dtPerpus = dtPerpus;
        tampilTransaksi(dtPerpus.transaksiList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfIdT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfTabelTransaksi = new javax.swing.JTable();
        tfProsesPengembalian = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transaksi Kembali - 205314152");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("ID Transaksi");

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfIdT, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIdT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar Koleksi"));

        tfTabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(tfTabelTransaksi);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tfProsesPengembalian.setText("Proses Pengembalian");
        tfProsesPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProsesPengembalianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 507, Short.MAX_VALUE)
                        .addComponent(tfProsesPengembalian)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfProsesPengembalian)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfProsesPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProsesPengembalianActionPerformed
//        if (!tfTabelTransaksi.getSelectionModel().isSelectionEmpty()) {
//            int selected = tfTabelTransaksi.getSelectedRow();         
//            String iD_transaksi = String.valueOf(tfTabelTransaksi.getValueAt(selected, 0));
//            LocalDate tglPinjam = LocalDate.parse(String.valueOf(tfTabelTransaksi.getValueAt(selected, 1)));
//            dtPerpus.dataPerpus.kembali(iD_transaksi, tglPinjam);
//            dtPerpus.refreshTransaksi();
//            tampilTransaksi(dtPerpus.transaksiList);
//            clrInput();
//            
//        }

        int a = tfTabelTransaksi.getSelectedRow();
        DefaultTableModel tbModelTransaksi = new DefaultTableModel();
        char tipe = dtPerpus.transaksiList.get(a).getId_transaksi().charAt(0);
        String vId = dtPerpus.transaksiList.get(a).getId_transaksi();
        switch (tipe) {
            case 'T':
                dtPerpus.dataPerpus.deleteTransaksi(vId);
                break;

            default:
                JOptionPane.showMessageDialog(this, "ID Transaksi tidak terdefinisi!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        dtPerpus.refreshTransaksi();
        clrInput();
        tampilTransaksi(dtPerpus.transaksiList);


    }//GEN-LAST:event_tfProsesPengembalianActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (cariTransaksi(tfIdT.getText()) == null) {
            JOptionPane.showMessageDialog(this, "ID Transaksi tidak terdefinisi!!", "Warning", JOptionPane.WARNING_MESSAGE);
            tampilTransaksi(dtPerpus.transaksiList);
            return;
        }
        Transaksi dtTransaksi = cariTransaksi(tfIdT.getText());
        ArrayList<Transaksi> tr = new ArrayList<Transaksi>();
        tr.add(dtTransaksi);
        tampilTransaksi(tr);
    }//GEN-LAST:event_jButton1ActionPerformed

    

    private void tampilTransaksi(ArrayList<Transaksi> arr) {
        String[] kolom = {"ID Transaksi", "Tanggal Pinjam", "Tanggal Kembali", "Denda", "ID Koleksi", "ID Peminjam"};
        Object[][] objData = new Object[arr.size()][4]; // 5 merupakan jumlah kolom
        int i = 0;
        for (Transaksi n : arr) {
            objData[i] = new String[]{n.getId_transaksi(), n.getTgl_pinjam().toString(),
                n.getTgl_kembali().toString(), String.valueOf(n.getDenda()), "koleksi", n.getPeminjam().getIdPeminjam()};
            i++;
        }
        DefaultTableModel tbModelTransaksi = new DefaultTableModel(objData, kolom) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        tfTabelTransaksi.repaint();
        tfTabelTransaksi.setModel(tbModelTransaksi);
    }

    private Transaksi cariTransaksi(String idTransaksi) {
        Iterator<Transaksi> iterator = dtPerpus.transaksiList.iterator();
        while (iterator.hasNext()) {
            Transaksi transaksi = iterator.next();
            if (transaksi.getId_transaksi().equals(idTransaksi)) {
                return transaksi;
            }
        }
        return null;
    }

    private void clrInput() {
        tfIdT.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dTransaksiKembali.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dTransaksiKembali.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dTransaksiKembali.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dTransaksiKembali.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dTransaksiKembali dialog = new dTransaksiKembali(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfIdT;
    private javax.swing.JButton tfProsesPengembalian;
    private javax.swing.JTable tfTabelTransaksi;
    // End of variables declaration//GEN-END:variables
}
